import React, { Component } from 'react';
import {
  Card,
  Table,
  Icon,
  Menu,
  Dropdown,
  Button,
  Label,
  Pagination,
  Row,
  Col,
  Form,
  Input,
  DatePicker,
  Select,
  Checkbox,
  Divider,
} from 'antd';
import { formatMessage, FormattedMessage } from 'umi/locale';
import PageHeaderWrapper from '@/components/PageHeaderWrapper';
import moment from 'moment';
import ModalGridView from '@/components/ModalGridView';
const FormItem = Form.Item;
const { RangePicker } = DatePicker;
import GridFilter from '@/components/GridFilter';
import ModalChangeDate from '@/components/ModalChangeDate';


const EditableContext = React.createContext();

class Requests extends Component {
  constructor(props) {
    super(props);
    this.state = {
      modalVisible: false,
      columns: [],
      searchercont: 0,
      tablecont: 24,
      isSearcher: false,
      filterForm:[],
      ModalData:{
        id:null,
        key:null,
        value:null
      },
      ShowModal: false,
      DataTable: {
        number: 0,
        size: 15, // in one page
        totalElements: 47983, //total of data
        totalPages: 3199,
        content: [
          {
            id: 'F83632ECE881416CAB52E4D7AE377B5C',
            lastPayDate: null,
            payAmount: '1935.00',
            refundEntryDate: '22.10.2018',
            appPayerDate: '17.10.2018',
            appEndDate: null,
            entryDate: '22.10.2018 15:11',
            receiptAppdateToFsms: null,
            refundDate: null,
            lastMedcarePayCount: null,
            personIin: '590110300316',
            personSurname: 'АБИТБЕКОВ',
            personFirstname: 'ЖЕТИГЕН',
            personPatronname: 'ШЫНЫБЕКОВИЧ',
            medinsStatus: null,
            refundPayAmount: 1935.0,
            refundStatus: null,
            appRefundStatus: 1,
            refundStatusText: null,
            refundDocumentList: null,
            daysLeft: null,
            changeDate: '22.10.2018 15:11',
            wsStatus: 0,
            wsStatusMessage: null,
            payPeriod: '012018',
            outPayOrderNum: 51300,
            applicationId: {
              id: '0B1F557C484F4D428E104ED265792040',
              appNumber: '8951',
              appDate: '19.10.2018',
              payOrderDate: '02.02.2018',
              payOrderNum: '72400899 ',
              reference: 'TRE351709239',
              refundCount: 10,
              receiptAppdateToFsms: null,
              appEndDate: null,
              dknpId: {
                id: '121',
                parentId: null,
                nameRu: 'Отчисления на обязательное социальное медицинское страхование',
                nameKz: null,
                code: null,
                shortname: 'Обяз.соц.мед.страх.',
                knpType: '1',
                letter: null,
                shortnameKz: null,
              },
            },
            gcvpReference: 'GCVP-00037805789',
            gcvpOrderNum: '34768765 ',
            gcvpOrderDate: '02.02.2018',
            rpmuCheckResult: null,
            dappRefundStatusId: {
              id: '10',
              parentId: null,
              nameRu: 'Принято',
              nameKz: 'Принято',
              code: '00010',
              version: 1.0,
            },
            ddenyReasonId: null,
            drefundReasonId: {
              id: '51E748D88D4637A6E054001B782A74A6',
              parentId: null,
              nameRu: 'Ошибочно перечислены',
              nameKz: null,
              code: '00111',
              version: 1.0,
            },
          },
          {
            id: '92D5475ADF23415099A647E85840ACE3',
            lastPayDate: null,
            payAmount: '425.00',
            refundEntryDate: '22.10.2018',
            appPayerDate: '08.10.2018',
            appEndDate: '25.10.2018',
            entryDate: '22.10.2018 15:05',
            receiptAppdateToFsms: '17.10.2018',
            refundDate: null,
            lastMedcarePayCount: null,
            personIin: '850803402503',
            personSurname: 'САРБАСОВА',
            personFirstname: 'ЭЛЬВИРА',
            personPatronname: 'ДУЙСЕНГАЛИЕВНА',
            medinsStatus: null,
            refundPayAmount: 425.0,
            refundStatus: 2,
            appRefundStatus: 1,
            refundStatusText: null,
            refundDocumentList: null,
            daysLeft: null,
            changeDate: '22.10.2018 15:05',
            wsStatus: 0,
            wsStatusMessage: null,
            payPeriod: '052018',
            outPayOrderNum: 51299,
            applicationId: {
              id: '074AC52DFC89483FB49C6076284CB0CE',
              appNumber: '7852',
              appDate: '22.10.2018',
              payOrderDate: '23.08.2018',
              payOrderNum: '002225978',
              reference: 'SB18824461967902',
              refundCount: 1,
              receiptAppdateToFsms: '17.10.2018',
              appEndDate: '25.10.2018',
              dknpId: {
                id: '121',
                parentId: null,
                nameRu: 'Отчисления на обязательное социальное медицинское страхование',
                nameKz: null,
                code: null,
                shortname: 'Обяз.соц.мед.страх.',
                knpType: '1',
                letter: null,
                shortnameKz: null,
              },
            },
            gcvpReference: 'GCVP-00039325545',
            gcvpOrderNum: '37801881 ',
            gcvpOrderDate: '25.08.2018',
            rpmuCheckResult: 'Не соответствует дата рождения;',
            dappRefundStatusId: {
              id: '4',
              parentId: null,
              nameRu: 'Обработано - отказано',
              nameKz: null,
              code: '00004',
              version: 1.0,
            },
            ddenyReasonId: {
              id: '1',
              parentId: null,
              nameRu: 'Частичный возврат по одному участнику',
              nameKz: 'Частичный возврат по одному участнику',
              code: '1',
              version: 1.0,
            },
            drefundReasonId: {
              id: '9',
              parentId: null,
              nameRu: 'Плательщиком или банком дважды перечислено',
              nameKz: 'Плательщиком или банком дважды перечислено',
              code: '9',
              version: 1.0,
            },
          },
          {
            id: 'F2458D2B3C8D40E7B0307D51CB9D1699',
            lastPayDate: null,
            payAmount: '450.00',
            refundEntryDate: '22.10.2018',
            appPayerDate: '19.10.2018',
            appEndDate: null,
            entryDate: '22.10.2018 12:43',
            receiptAppdateToFsms: null,
            refundDate: null,
            lastMedcarePayCount: null,
            personIin: '731201401557',
            personSurname: 'КАРЫБАЕВА',
            personFirstname: 'ЗАМЗАГУЛ',
            personPatronname: 'БЕКЕНОВНА',
            medinsStatus: null,
            refundPayAmount: 450.0,
            refundStatus: null,
            appRefundStatus: 1,
            refundStatusText: null,
            refundDocumentList: null,
            daysLeft: null,
            changeDate: '22.10.2018 12:43',
            wsStatus: 0,
            wsStatusMessage: null,
            payPeriod: '062018',
            outPayOrderNum: 51288,
            applicationId: {
              id: 'AD511E558DC7498FB33F4B0115065541',
              appNumber: '8994',
              appDate: '22.10.2018',
              payOrderDate: '23.07.2018',
              payOrderNum: '657578   ',
              reference: 'IOA0000000300225',
              refundCount: 4,
              receiptAppdateToFsms: null,
              appEndDate: null,
              dknpId: {
                id: '121',
                parentId: null,
                nameRu: 'Отчисления на обязательное социальное медицинское страхование',
                nameKz: null,
                code: null,
                shortname: 'Обяз.соц.мед.страх.',
                knpType: '1',
                letter: null,
                shortnameKz: null,
              },
            },
            gcvpReference: 'GCVP-00039070777',
            gcvpOrderNum: '37292379 ',
            gcvpOrderDate: '23.07.2018',
            rpmuCheckResult: null,
            dappRefundStatusId: {
              id: '10',
              parentId: null,
              nameRu: 'Принято',
              nameKz: 'Принято',
              code: '00010',
              version: 1.0,
            },
            ddenyReasonId: null,
            drefundReasonId: {
              id: '9',
              parentId: null,
              nameRu: 'Плательщиком или банком дважды перечислено',
              nameKz: 'Плательщиком или банком дважды перечислено',
              code: '9',
              version: 1.0,
            },
          },
          {
            id: '3B415077BCA0405593EDA3151369451F',
            lastPayDate: null,
            payAmount: '1035.00',
            refundEntryDate: '22.10.2018',
            appPayerDate: '19.10.2018',
            appEndDate: null,
            entryDate: '22.10.2018 12:43',
            receiptAppdateToFsms: null,
            refundDate: null,
            lastMedcarePayCount: null,
            personIin: '970714351661',
            personSurname: 'КРАМСКОЙ',
            personFirstname: 'ВЛАДИСЛАВ',
            personPatronname: 'НИКОЛАЕВИЧ',
            medinsStatus: null,
            refundPayAmount: 1035.0,
            refundStatus: null,
            appRefundStatus: 1,
            refundStatusText: null,
            refundDocumentList: null,
            daysLeft: null,
            changeDate: '22.10.2018 12:43',
            wsStatus: 0,
            wsStatusMessage: null,
            payPeriod: '062018',
            outPayOrderNum: 51286,
            applicationId: {
              id: 'AD511E558DC7498FB33F4B0115065541',
              appNumber: '8994',
              appDate: '22.10.2018',
              payOrderDate: '23.07.2018',
              payOrderNum: '657578   ',
              reference: 'IOA0000000300225',
              refundCount: 4,
              receiptAppdateToFsms: null,
              appEndDate: null,
              dknpId: {
                id: '121',
                parentId: null,
                nameRu: 'Отчисления на обязательное социальное медицинское страхование',
                nameKz: null,
                code: null,
                shortname: 'Обяз.соц.мед.страх.',
                knpType: '1',
                letter: null,
                shortnameKz: null,
              },
            },
            gcvpReference: 'GCVP-00039070777',
            gcvpOrderNum: '37292379 ',
            gcvpOrderDate: '23.07.2018',
            rpmuCheckResult: null,
            dappRefundStatusId: {
              id: '10',
              parentId: null,
              nameRu: 'Принято',
              nameKz: 'Принято',
              code: '00010',
              version: 1.0,
            },
            ddenyReasonId: null,
            drefundReasonId: {
              id: '9',
              parentId: null,
              nameRu: 'Плательщиком или банком дважды перечислено',
              nameKz: 'Плательщиком или банком дважды перечислено',
              code: '9',
              version: 1.0,
            },
          },
          {
            id: 'E94C941ECF7740609DC2D02ED8A8352C',
            lastPayDate: null,
            payAmount: '450.00',
            refundEntryDate: '22.10.2018',
            appPayerDate: '19.10.2018',
            appEndDate: null,
            entryDate: '22.10.2018 12:43',
            receiptAppdateToFsms: null,
            refundDate: null,
            lastMedcarePayCount: null,
            personIin: '731201401557',
            personSurname: 'КАРЫБАЕВА',
            personFirstname: 'ЗАМЗАГУЛ',
            personPatronname: 'БЕКЕНОВНА',
            medinsStatus: null,
            refundPayAmount: 450.0,
            refundStatus: null,
            appRefundStatus: 1,
            refundStatusText: null,
            refundDocumentList: null,
            daysLeft: null,
            changeDate: '22.10.2018 12:43',
            wsStatus: 0,
            wsStatusMessage: null,
            payPeriod: '022018',
            outPayOrderNum: 51287,
            applicationId: {
              id: 'AD511E558DC7498FB33F4B0115065541',
              appNumber: '8994',
              appDate: '22.10.2018',
              payOrderDate: '23.07.2018',
              payOrderNum: '657578   ',
              reference: 'IOA0000000300225',
              refundCount: 4,
              receiptAppdateToFsms: null,
              appEndDate: null,
              dknpId: {
                id: '121',
                parentId: null,
                nameRu: 'Отчисления на обязательное социальное медицинское страхование',
                nameKz: null,
                code: null,
                shortname: 'Обяз.соц.мед.страх.',
                knpType: '1',
                letter: null,
                shortnameKz: null,
              },
            },
            gcvpReference: 'GCVP-00039070777',
            gcvpOrderNum: '37292379 ',
            gcvpOrderDate: '23.07.2018',
            rpmuCheckResult: null,
            dappRefundStatusId: {
              id: '10',
              parentId: null,
              nameRu: 'Принято',
              nameKz: 'Принято',
              code: '00010',
              version: 1.0,
            },
            ddenyReasonId: null,
            drefundReasonId: {
              id: '9',
              parentId: null,
              nameRu: 'Плательщиком или банком дважды перечислено',
              nameKz: 'Плательщиком или банком дважды перечислено',
              code: '9',
              version: 1.0,
            },
          },
          {
            id: '3872890E9A9F46AAB67B754020E645F9',
            lastPayDate: null,
            payAmount: '833.00',
            refundEntryDate: '22.10.2018',
            appPayerDate: '22.10.2018',
            appEndDate: null,
            entryDate: '22.10.2018 17:51',
            receiptAppdateToFsms: null,
            refundDate: null,
            lastMedcarePayCount: null,
            personIin: '801218301320',
            personSurname: 'ШПЕКОВ',
            personFirstname: 'АЗАТ',
            personPatronname: 'САЛИМОВИЧ',
            medinsStatus: null,
            refundPayAmount: 833.0,
            refundStatus: null,
            appRefundStatus: 1,
            refundStatusText: null,
            refundDocumentList: null,
            daysLeft: null,
            changeDate: '22.10.2018 17:51',
            wsStatus: 0,
            wsStatusMessage: null,
            payPeriod: '082018',
            outPayOrderNum: 51324,
            applicationId: {
              id: 'CFC7944BE75544BDA78790377D9C2E04',
              appNumber: '9232',
              appDate: '22.10.2018',
              payOrderDate: '19.09.2018',
              payOrderNum: '2086     ',
              reference: '5318919277012649',
              refundCount: 1,
              receiptAppdateToFsms: null,
              appEndDate: null,
              dknpId: {
                id: '121',
                parentId: null,
                nameRu: 'Отчисления на обязательное социальное медицинское страхование',
                nameKz: null,
                code: null,
                shortname: 'Обяз.соц.мед.страх.',
                knpType: '1',
                letter: null,
                shortnameKz: null,
              },
            },
            gcvpReference: 'GCVP-00039556609',
            gcvpOrderNum: '38210729 ',
            gcvpOrderDate: '20.09.2018',
            rpmuCheckResult: null,
            dappRefundStatusId: {
              id: '10',
              parentId: null,
              nameRu: 'Принято',
              nameKz: 'Принято',
              code: '00010',
              version: 1.0,
            },
            ddenyReasonId: null,
            drefundReasonId: {
              id: '51E748D88D4637A6E054001B782A74A6',
              parentId: null,
              nameRu: 'Ошибочно перечислены',
              nameKz: null,
              code: '00111',
              version: 1.0,
            },
          },
          {
            id: 'E60DD0F935A241A5B9826E04337D6C19',
            lastPayDate: null,
            payAmount: '1247.00',
            refundEntryDate: '22.10.2018',
            appPayerDate: '17.10.2018',
            appEndDate: null,
            entryDate: '22.10.2018 15:11',
            receiptAppdateToFsms: null,
            refundDate: null,
            lastMedcarePayCount: null,
            personIin: '770715450099',
            personSurname: 'СЕИТОВА',
            personFirstname: 'ИНДИРА',
            personPatronname: 'САПУАНОВНА',
            medinsStatus: null,
            refundPayAmount: 1247.0,
            refundStatus: null,
            appRefundStatus: 1,
            refundStatusText: null,
            refundDocumentList: null,
            daysLeft: null,
            changeDate: '22.10.2018 15:11',
            wsStatus: 0,
            wsStatusMessage: null,
            payPeriod: '012018',
            outPayOrderNum: 51309,
            applicationId: {
              id: '0B1F557C484F4D428E104ED265792040',
              appNumber: '8951',
              appDate: '19.10.2018',
              payOrderDate: '02.02.2018',
              payOrderNum: '72400899 ',
              reference: 'TRE351709239',
              refundCount: 10,
              receiptAppdateToFsms: null,
              appEndDate: null,
              dknpId: {
                id: '121',
                parentId: null,
                nameRu: 'Отчисления на обязательное социальное медицинское страхование',
                nameKz: null,
                code: null,
                shortname: 'Обяз.соц.мед.страх.',
                knpType: '1',
                letter: null,
                shortnameKz: null,
              },
            },
            gcvpReference: 'GCVP-00037805789',
            gcvpOrderNum: '34768765 ',
            gcvpOrderDate: '02.02.2018',
            rpmuCheckResult: null,
            dappRefundStatusId: {
              id: '10',
              parentId: null,
              nameRu: 'Принято',
              nameKz: 'Принято',
              code: '00010',
              version: 1.0,
            },
            ddenyReasonId: null,
            drefundReasonId: {
              id: '51E748D88D4637A6E054001B782A74A6',
              parentId: null,
              nameRu: 'Ошибочно перечислены',
              nameKz: null,
              code: '00111',
              version: 1.0,
            },
          },
          {
            id: '99FD3EB4D56F4018BDB7C8BFCB6C10BE',
            lastPayDate: null,
            payAmount: '1772.00',
            refundEntryDate: '22.10.2018',
            appPayerDate: '17.10.2018',
            appEndDate: null,
            entryDate: '22.10.2018 15:11',
            receiptAppdateToFsms: null,
            refundDate: null,
            lastMedcarePayCount: null,
            personIin: '700116302415',
            personSurname: 'МЫЛТЫКБАЕВ',
            personFirstname: 'ДАУЛЕТ',
            personPatronname: 'ТУРСЫНГАЗЫЕВИЧ',
            medinsStatus: null,
            refundPayAmount: 1772.0,
            refundStatus: null,
            appRefundStatus: 1,
            refundStatusText: null,
            refundDocumentList: null,
            daysLeft: null,
            changeDate: '22.10.2018 15:11',
            wsStatus: 0,
            wsStatusMessage: null,
            payPeriod: '012018',
            outPayOrderNum: 51308,
            applicationId: {
              id: '0B1F557C484F4D428E104ED265792040',
              appNumber: '8951',
              appDate: '19.10.2018',
              payOrderDate: '02.02.2018',
              payOrderNum: '72400899 ',
              reference: 'TRE351709239',
              refundCount: 10,
              receiptAppdateToFsms: null,
              appEndDate: null,
              dknpId: {
                id: '121',
                parentId: null,
                nameRu: 'Отчисления на обязательное социальное медицинское страхование',
                nameKz: null,
                code: null,
                shortname: 'Обяз.соц.мед.страх.',
                knpType: '1',
                letter: null,
                shortnameKz: null,
              },
            },
            gcvpReference: 'GCVP-00037805789',
            gcvpOrderNum: '34768765 ',
            gcvpOrderDate: '02.02.2018',
            rpmuCheckResult: null,
            dappRefundStatusId: {
              id: '10',
              parentId: null,
              nameRu: 'Принято',
              nameKz: 'Принято',
              code: '00010',
              version: 1.0,
            },
            ddenyReasonId: null,
            drefundReasonId: {
              id: '51E748D88D4637A6E054001B782A74A6',
              parentId: null,
              nameRu: 'Ошибочно перечислены',
              nameKz: null,
              code: '00111',
              version: 1.0,
            },
          },
          {
            id: '95627EBBAA814CF1B880AECE2FF75BB9',
            lastPayDate: null,
            payAmount: '1620.00',
            refundEntryDate: '22.10.2018',
            appPayerDate: '17.10.2018',
            appEndDate: null,
            entryDate: '22.10.2018 15:11',
            receiptAppdateToFsms: null,
            refundDate: null,
            lastMedcarePayCount: null,
            personIin: '740602400356',
            personSurname: 'КАЛИЕВА',
            personFirstname: 'АСЕТ',
            personPatronname: 'АХМЕТОВНА',
            medinsStatus: null,
            refundPayAmount: 1620.0,
            refundStatus: null,
            appRefundStatus: 1,
            refundStatusText: null,
            refundDocumentList: null,
            daysLeft: null,
            changeDate: '22.10.2018 15:11',
            wsStatus: 0,
            wsStatusMessage: null,
            payPeriod: '012018',
            outPayOrderNum: 51307,
            applicationId: {
              id: '0B1F557C484F4D428E104ED265792040',
              appNumber: '8951',
              appDate: '19.10.2018',
              payOrderDate: '02.02.2018',
              payOrderNum: '72400899 ',
              reference: 'TRE351709239',
              refundCount: 10,
              receiptAppdateToFsms: null,
              appEndDate: null,
              dknpId: {
                id: '121',
                parentId: null,
                nameRu: 'Отчисления на обязательное социальное медицинское страхование',
                nameKz: null,
                code: null,
                shortname: 'Обяз.соц.мед.страх.',
                knpType: '1',
                letter: null,
                shortnameKz: null,
              },
            },
            gcvpReference: 'GCVP-00037805789',
            gcvpOrderNum: '34768765 ',
            gcvpOrderDate: '02.02.2018',
            rpmuCheckResult: null,
            dappRefundStatusId: {
              id: '10',
              parentId: null,
              nameRu: 'Принято',
              nameKz: 'Принято',
              code: '00010',
              version: 1.0,
            },
            ddenyReasonId: null,
            drefundReasonId: {
              id: '51E748D88D4637A6E054001B782A74A6',
              parentId: null,
              nameRu: 'Ошибочно перечислены',
              nameKz: null,
              code: '00111',
              version: 1.0,
            },
          },
          {
            id: '2657736C188C41DA891A4890318D6250',
            lastPayDate: null,
            payAmount: '2254.00',
            refundEntryDate: '22.10.2018',
            appPayerDate: '17.10.2018',
            appEndDate: null,
            entryDate: '22.10.2018 15:11',
            receiptAppdateToFsms: null,
            refundDate: null,
            lastMedcarePayCount: null,
            personIin: '650823301959',
            personSurname: 'ИМАНКУЛОВ',
            personFirstname: 'ЕРЛАН',
            personPatronname: 'КАБЫЛГАЛИЕВИЧ',
            medinsStatus: null,
            refundPayAmount: 2254.0,
            refundStatus: null,
            appRefundStatus: 1,
            refundStatusText: null,
            refundDocumentList: null,
            daysLeft: null,
            changeDate: '22.10.2018 15:11',
            wsStatus: 0,
            wsStatusMessage: null,
            payPeriod: '012018',
            outPayOrderNum: 51306,
            applicationId: {
              id: '0B1F557C484F4D428E104ED265792040',
              appNumber: '8951',
              appDate: '19.10.2018',
              payOrderDate: '02.02.2018',
              payOrderNum: '72400899 ',
              reference: 'TRE351709239',
              refundCount: 10,
              receiptAppdateToFsms: null,
              appEndDate: null,
              dknpId: {
                id: '121',
                parentId: null,
                nameRu: 'Отчисления на обязательное социальное медицинское страхование',
                nameKz: null,
                code: null,
                shortname: 'Обяз.соц.мед.страх.',
                knpType: '1',
                letter: null,
                shortnameKz: null,
              },
            },
            gcvpReference: 'GCVP-00037805789',
            gcvpOrderNum: '34768765 ',
            gcvpOrderDate: '02.02.2018',
            rpmuCheckResult: null,
            dappRefundStatusId: {
              id: '10',
              parentId: null,
              nameRu: 'Принято',
              nameKz: 'Принято',
              code: '00010',
              version: 1.0,
            },
            ddenyReasonId: null,
            drefundReasonId: {
              id: '51E748D88D4637A6E054001B782A74A6',
              parentId: null,
              nameRu: 'Ошибочно перечислены',
              nameKz: null,
              code: '00111',
              version: 1.0,
            },
          },
          {
            id: '0D259975ADF546A191703144B9C6205C',
            lastPayDate: null,
            payAmount: '2559.00',
            refundEntryDate: '22.10.2018',
            appPayerDate: '17.10.2018',
            appEndDate: null,
            entryDate: '22.10.2018 15:11',
            receiptAppdateToFsms: null,
            refundDate: null,
            lastMedcarePayCount: null,
            personIin: '640808302468',
            personSurname: 'ЖАРУЛЛАЕВ',
            personFirstname: 'ШАХИМУРАТ',
            personPatronname: 'РАБУЛЛАЕВИЧ',
            medinsStatus: null,
            refundPayAmount: 2559.0,
            refundStatus: null,
            appRefundStatus: 1,
            refundStatusText: null,
            refundDocumentList: null,
            daysLeft: null,
            changeDate: '22.10.2018 15:11',
            wsStatus: 0,
            wsStatusMessage: null,
            payPeriod: '012018',
            outPayOrderNum: 51305,
            applicationId: {
              id: '0B1F557C484F4D428E104ED265792040',
              appNumber: '8951',
              appDate: '19.10.2018',
              payOrderDate: '02.02.2018',
              payOrderNum: '72400899 ',
              reference: 'TRE351709239',
              refundCount: 10,
              receiptAppdateToFsms: null,
              appEndDate: null,
              dknpId: {
                id: '121',
                parentId: null,
                nameRu: 'Отчисления на обязательное социальное медицинское страхование',
                nameKz: null,
                code: null,
                shortname: 'Обяз.соц.мед.страх.',
                knpType: '1',
                letter: null,
                shortnameKz: null,
              },
            },
            gcvpReference: 'GCVP-00037805789',
            gcvpOrderNum: '34768765 ',
            gcvpOrderDate: '02.02.2018',
            rpmuCheckResult: null,
            dappRefundStatusId: {
              id: '10',
              parentId: null,
              nameRu: 'Принято',
              nameKz: 'Принято',
              code: '00010',
              version: 1.0,
            },
            ddenyReasonId: null,
            drefundReasonId: {
              id: '51E748D88D4637A6E054001B782A74A6',
              parentId: null,
              nameRu: 'Ошибочно перечислены',
              nameKz: null,
              code: '00111',
              version: 1.0,
            },
          },
          {
            id: 'CC07293BCFA9467ABAAE85CEC22ECADD',
            lastPayDate: null,
            payAmount: '2100.00',
            refundEntryDate: '22.10.2018',
            appPayerDate: '17.10.2018',
            appEndDate: null,
            entryDate: '22.10.2018 15:11',
            receiptAppdateToFsms: null,
            refundDate: null,
            lastMedcarePayCount: null,
            personIin: '621010302607',
            personSurname: 'ДУЙСЕНБАЕВ',
            personFirstname: 'ЖУМАБЕК',
            personPatronname: 'ЖУМАТАЕВИЧ',
            medinsStatus: null,
            refundPayAmount: 2100.0,
            refundStatus: null,
            appRefundStatus: 1,
            refundStatusText: null,
            refundDocumentList: null,
            daysLeft: null,
            changeDate: '22.10.2018 15:11',
            wsStatus: 0,
            wsStatusMessage: null,
            payPeriod: '012018',
            outPayOrderNum: 51304,
            applicationId: {
              id: '0B1F557C484F4D428E104ED265792040',
              appNumber: '8951',
              appDate: '19.10.2018',
              payOrderDate: '02.02.2018',
              payOrderNum: '72400899 ',
              reference: 'TRE351709239',
              refundCount: 10,
              receiptAppdateToFsms: null,
              appEndDate: null,
              dknpId: {
                id: '121',
                parentId: null,
                nameRu: 'Отчисления на обязательное социальное медицинское страхование',
                nameKz: null,
                code: null,
                shortname: 'Обяз.соц.мед.страх.',
                knpType: '1',
                letter: null,
                shortnameKz: null,
              },
            },
            gcvpReference: 'GCVP-00037805789',
            gcvpOrderNum: '34768765 ',
            gcvpOrderDate: '02.02.2018',
            rpmuCheckResult: null,
            dappRefundStatusId: {
              id: '10',
              parentId: null,
              nameRu: 'Принято',
              nameKz: 'Принято',
              code: '00010',
              version: 1.0,
            },
            ddenyReasonId: null,
            drefundReasonId: {
              id: '51E748D88D4637A6E054001B782A74A6',
              parentId: null,
              nameRu: 'Ошибочно перечислены',
              nameKz: null,
              code: '00111',
              version: 1.0,
            },
          },
          {
            id: '973EF2E9DCBC44ACAC77866AD9C413AB',
            lastPayDate: null,
            payAmount: '2450.00',
            refundEntryDate: '22.10.2018',
            appPayerDate: '17.10.2018',
            appEndDate: null,
            entryDate: '22.10.2018 15:11',
            receiptAppdateToFsms: null,
            refundDate: null,
            lastMedcarePayCount: null,
            personIin: '640203350449',
            personSurname: 'ГУСЕВ',
            personFirstname: 'ПЕТР',
            personPatronname: 'АНДРЕЕВИЧ',
            medinsStatus: null,
            refundPayAmount: 2450.0,
            refundStatus: null,
            appRefundStatus: 1,
            refundStatusText: null,
            refundDocumentList: null,
            daysLeft: null,
            changeDate: '22.10.2018 15:11',
            wsStatus: 0,
            wsStatusMessage: null,
            payPeriod: '012018',
            outPayOrderNum: 51303,
            applicationId: {
              id: '0B1F557C484F4D428E104ED265792040',
              appNumber: '8951',
              appDate: '19.10.2018',
              payOrderDate: '02.02.2018',
              payOrderNum: '72400899 ',
              reference: 'TRE351709239',
              refundCount: 10,
              receiptAppdateToFsms: null,
              appEndDate: null,
              dknpId: {
                id: '121',
                parentId: null,
                nameRu: 'Отчисления на обязательное социальное медицинское страхование',
                nameKz: null,
                code: null,
                shortname: 'Обяз.соц.мед.страх.',
                knpType: '1',
                letter: null,
                shortnameKz: null,
              },
            },
            gcvpReference: 'GCVP-00037805789',
            gcvpOrderNum: '34768765 ',
            gcvpOrderDate: '02.02.2018',
            rpmuCheckResult: null,
            dappRefundStatusId: {
              id: '10',
              parentId: null,
              nameRu: 'Принято',
              nameKz: 'Принято',
              code: '00010',
              version: 1.0,
            },
            ddenyReasonId: null,
            drefundReasonId: {
              id: '51E748D88D4637A6E054001B782A74A6',
              parentId: null,
              nameRu: 'Ошибочно перечислены',
              nameKz: null,
              code: '00111',
              version: 1.0,
            },
          },
          {
            id: '06D99163A64F4D578E7DF95641CB923A',
            lastPayDate: null,
            payAmount: '1935.00',
            refundEntryDate: '22.10.2018',
            appPayerDate: '17.10.2018',
            appEndDate: null,
            entryDate: '22.10.2018 15:11',
            receiptAppdateToFsms: null,
            refundDate: null,
            lastMedcarePayCount: null,
            personIin: '680110303082',
            personSurname: 'БОНДАРЕВ',
            personFirstname: 'ВЛАДИМИР',
            personPatronname: 'ВИКТОРОВИЧ',
            medinsStatus: null,
            refundPayAmount: 1935.0,
            refundStatus: null,
            appRefundStatus: 1,
            refundStatusText: null,
            refundDocumentList: null,
            daysLeft: null,
            changeDate: '22.10.2018 15:11',
            wsStatus: 0,
            wsStatusMessage: null,
            payPeriod: '012018',
            outPayOrderNum: 51302,
            applicationId: {
              id: '0B1F557C484F4D428E104ED265792040',
              appNumber: '8951',
              appDate: '19.10.2018',
              payOrderDate: '02.02.2018',
              payOrderNum: '72400899 ',
              reference: 'TRE351709239',
              refundCount: 10,
              receiptAppdateToFsms: null,
              appEndDate: null,
              dknpId: {
                id: '121',
                parentId: null,
                nameRu: 'Отчисления на обязательное социальное медицинское страхование',
                nameKz: null,
                code: null,
                shortname: 'Обяз.соц.мед.страх.',
                knpType: '1',
                letter: null,
                shortnameKz: null,
              },
            },
            gcvpReference: 'GCVP-00037805789',
            gcvpOrderNum: '34768765 ',
            gcvpOrderDate: '02.02.2018',
            rpmuCheckResult: null,
            dappRefundStatusId: {
              id: '10',
              parentId: null,
              nameRu: 'Принято',
              nameKz: 'Принято',
              code: '00010',
              version: 1.0,
            },
            ddenyReasonId: null,
            drefundReasonId: {
              id: '51E748D88D4637A6E054001B782A74A6',
              parentId: null,
              nameRu: 'Ошибочно перечислены',
              nameKz: null,
              code: '00111',
              version: 1.0,
            },
          },
          {
            id: '6A6A4A3F6B834243BE4E05031F83E277',
            lastPayDate: null,
            payAmount: '1797.00',
            refundEntryDate: '22.10.2018',
            appPayerDate: '17.10.2018',
            appEndDate: null,
            entryDate: '22.10.2018 15:11',
            receiptAppdateToFsms: null,
            refundDate: null,
            lastMedcarePayCount: null,
            personIin: '700127302777',
            personSurname: 'АЗАМАТОВ',
            personFirstname: 'САБЫРГАЛИ',
            personPatronname: 'КАИРБОЛАТОВИЧ',
            medinsStatus: null,
            refundPayAmount: 1797.0,
            refundStatus: null,
            appRefundStatus: 1,
            refundStatusText: null,
            refundDocumentList: null,
            daysLeft: null,
            changeDate: '22.10.2018 15:11',
            wsStatus: 0,
            wsStatusMessage: null,
            payPeriod: '012018',
            outPayOrderNum: 51301,
            applicationId: {
              id: '0B1F557C484F4D428E104ED265792040',
              appNumber: '8951',
              appDate: '19.10.2018',
              payOrderDate: '02.02.2018',
              payOrderNum: '72400899 ',
              reference: 'TRE351709239',
              refundCount: 10,
              receiptAppdateToFsms: null,
              appEndDate: null,
              dknpId: {
                id: '121',
                parentId: null,
                nameRu: 'Отчисления на обязательное социальное медицинское страхование',
                nameKz: null,
                code: null,
                shortname: 'Обяз.соц.мед.страх.',
                knpType: '1',
                letter: null,
                shortnameKz: null,
              },
            },
            gcvpReference: 'GCVP-00037805789',
            gcvpOrderNum: '34768765 ',
            gcvpOrderDate: '02.02.2018',
            rpmuCheckResult: null,
            dappRefundStatusId: {
              id: '10',
              parentId: null,
              nameRu: 'Принято',
              nameKz: 'Принято',
              code: '00010',
              version: 1.0,
            },
            ddenyReasonId: null,
            drefundReasonId: {
              id: '51E748D88D4637A6E054001B782A74A6',
              parentId: null,
              nameRu: 'Ошибочно перечислены',
              nameKz: null,
              code: '00111',
              version: 1.0,
            },
          },
          {
            id: 'F83632ECE881416CAB52E4D7AE377B5C',
            lastPayDate: null,
            payAmount: '1935.00',
            refundEntryDate: '22.10.2018',
            appPayerDate: '17.10.2018',
            appEndDate: null,
            entryDate: '22.10.2018 15:11',
            receiptAppdateToFsms: null,
            refundDate: null,
            lastMedcarePayCount: null,
            personIin: '590110300316',
            personSurname: 'АБИТБЕКОВ',
            personFirstname: 'ЖЕТИГЕН',
            personPatronname: 'ШЫНЫБЕКОВИЧ',
            medinsStatus: null,
            refundPayAmount: 1935.0,
            refundStatus: null,
            appRefundStatus: 1,
            refundStatusText: null,
            refundDocumentList: null,
            daysLeft: null,
            changeDate: '22.10.2018 15:11',
            wsStatus: 0,
            wsStatusMessage: null,
            payPeriod: '012018',
            outPayOrderNum: 51300,
            applicationId: {
              id: '0B1F557C484F4D428E104ED265792040',
              appNumber: '8951',
              appDate: '19.10.2018',
              payOrderDate: '02.02.2018',
              payOrderNum: '72400899 ',
              reference: 'TRE351709239',
              refundCount: 10,
              receiptAppdateToFsms: null,
              appEndDate: null,
              dknpId: {
                id: '121',
                parentId: null,
                nameRu: 'Отчисления на обязательное социальное медицинское страхование',
                nameKz: null,
                code: null,
                shortname: 'Обяз.соц.мед.страх.',
                knpType: '1',
                letter: null,
                shortnameKz: null,
              },
            },
            gcvpReference: 'GCVP-00037805789',
            gcvpOrderNum: '34768765 ',
            gcvpOrderDate: '02.02.2018',
            rpmuCheckResult: null,
            dappRefundStatusId: {
              id: '10',
              parentId: null,
              nameRu: 'Принято',
              nameKz: 'Принято',
              code: '00010',
              version: 1.0,
            },
            ddenyReasonId: null,
            drefundReasonId: {
              id: '51E748D88D4637A6E054001B782A74A6',
              parentId: null,
              nameRu: 'Ошибочно перечислены',
              nameKz: null,
              code: '00111',
              version: 1.0,
            },
          },
          {
            id: '92D5475ADF23415099A647E85840ACE3',
            lastPayDate: null,
            payAmount: '425.00',
            refundEntryDate: '22.10.2018',
            appPayerDate: '08.10.2018',
            appEndDate: '25.10.2018',
            entryDate: '22.10.2018 15:05',
            receiptAppdateToFsms: '17.10.2018',
            refundDate: null,
            lastMedcarePayCount: null,
            personIin: '850803402503',
            personSurname: 'САРБАСОВА',
            personFirstname: 'ЭЛЬВИРА',
            personPatronname: 'ДУЙСЕНГАЛИЕВНА',
            medinsStatus: null,
            refundPayAmount: 425.0,
            refundStatus: 2,
            appRefundStatus: 1,
            refundStatusText: null,
            refundDocumentList: null,
            daysLeft: null,
            changeDate: '22.10.2018 15:05',
            wsStatus: 0,
            wsStatusMessage: null,
            payPeriod: '052018',
            outPayOrderNum: 51299,
            applicationId: {
              id: '074AC52DFC89483FB49C6076284CB0CE',
              appNumber: '7852',
              appDate: '22.10.2018',
              payOrderDate: '23.08.2018',
              payOrderNum: '002225978',
              reference: 'SB18824461967902',
              refundCount: 1,
              receiptAppdateToFsms: '17.10.2018',
              appEndDate: '25.10.2018',
              dknpId: {
                id: '121',
                parentId: null,
                nameRu: 'Отчисления на обязательное социальное медицинское страхование',
                nameKz: null,
                code: null,
                shortname: 'Обяз.соц.мед.страх.',
                knpType: '1',
                letter: null,
                shortnameKz: null,
              },
            },
            gcvpReference: 'GCVP-00039325545',
            gcvpOrderNum: '37801881 ',
            gcvpOrderDate: '25.08.2018',
            rpmuCheckResult: 'Не соответствует дата рождения;',
            dappRefundStatusId: {
              id: '4',
              parentId: null,
              nameRu: 'Обработано - отказано',
              nameKz: null,
              code: '00004',
              version: 1.0,
            },
            ddenyReasonId: {
              id: '1',
              parentId: null,
              nameRu: 'Частичный возврат по одному участнику',
              nameKz: 'Частичный возврат по одному участнику',
              code: '1',
              version: 1.0,
            },
            drefundReasonId: {
              id: '9',
              parentId: null,
              nameRu: 'Плательщиком или банком дважды перечислено',
              nameKz: 'Плательщиком или банком дважды перечислено',
              code: '9',
              version: 1.0,
            },
          },
          {
            id: 'F2458D2B3C8D40E7B0307D51CB9D1699',
            lastPayDate: null,
            payAmount: '450.00',
            refundEntryDate: '22.10.2018',
            appPayerDate: '19.10.2018',
            appEndDate: null,
            entryDate: '22.10.2018 12:43',
            receiptAppdateToFsms: null,
            refundDate: null,
            lastMedcarePayCount: null,
            personIin: '731201401557',
            personSurname: 'КАРЫБАЕВА',
            personFirstname: 'ЗАМЗАГУЛ',
            personPatronname: 'БЕКЕНОВНА',
            medinsStatus: null,
            refundPayAmount: 450.0,
            refundStatus: null,
            appRefundStatus: 1,
            refundStatusText: null,
            refundDocumentList: null,
            daysLeft: null,
            changeDate: '22.10.2018 12:43',
            wsStatus: 0,
            wsStatusMessage: null,
            payPeriod: '062018',
            outPayOrderNum: 51288,
            applicationId: {
              id: 'AD511E558DC7498FB33F4B0115065541',
              appNumber: '8994',
              appDate: '22.10.2018',
              payOrderDate: '23.07.2018',
              payOrderNum: '657578   ',
              reference: 'IOA0000000300225',
              refundCount: 4,
              receiptAppdateToFsms: null,
              appEndDate: null,
              dknpId: {
                id: '121',
                parentId: null,
                nameRu: 'Отчисления на обязательное социальное медицинское страхование',
                nameKz: null,
                code: null,
                shortname: 'Обяз.соц.мед.страх.',
                knpType: '1',
                letter: null,
                shortnameKz: null,
              },
            },
            gcvpReference: 'GCVP-00039070777',
            gcvpOrderNum: '37292379 ',
            gcvpOrderDate: '23.07.2018',
            rpmuCheckResult: null,
            dappRefundStatusId: {
              id: '10',
              parentId: null,
              nameRu: 'Принято',
              nameKz: 'Принято',
              code: '00010',
              version: 1.0,
            },
            ddenyReasonId: null,
            drefundReasonId: {
              id: '9',
              parentId: null,
              nameRu: 'Плательщиком или банком дважды перечислено',
              nameKz: 'Плательщиком или банком дважды перечислено',
              code: '9',
              version: 1.0,
            },
          },
          {
            id: '3B415077BCA0405593EDA3151369451F',
            lastPayDate: null,
            payAmount: '1035.00',
            refundEntryDate: '22.10.2018',
            appPayerDate: '19.10.2018',
            appEndDate: null,
            entryDate: '22.10.2018 12:43',
            receiptAppdateToFsms: null,
            refundDate: null,
            lastMedcarePayCount: null,
            personIin: '970714351661',
            personSurname: 'КРАМСКОЙ',
            personFirstname: 'ВЛАДИСЛАВ',
            personPatronname: 'НИКОЛАЕВИЧ',
            medinsStatus: null,
            refundPayAmount: 1035.0,
            refundStatus: null,
            appRefundStatus: 1,
            refundStatusText: null,
            refundDocumentList: null,
            daysLeft: null,
            changeDate: '22.10.2018 12:43',
            wsStatus: 0,
            wsStatusMessage: null,
            payPeriod: '062018',
            outPayOrderNum: 51286,
            applicationId: {
              id: 'AD511E558DC7498FB33F4B0115065541',
              appNumber: '8994',
              appDate: '22.10.2018',
              payOrderDate: '23.07.2018',
              payOrderNum: '657578   ',
              reference: 'IOA0000000300225',
              refundCount: 4,
              receiptAppdateToFsms: null,
              appEndDate: null,
              dknpId: {
                id: '121',
                parentId: null,
                nameRu: 'Отчисления на обязательное социальное медицинское страхование',
                nameKz: null,
                code: null,
                shortname: 'Обяз.соц.мед.страх.',
                knpType: '1',
                letter: null,
                shortnameKz: null,
              },
            },
            gcvpReference: 'GCVP-00039070777',
            gcvpOrderNum: '37292379 ',
            gcvpOrderDate: '23.07.2018',
            rpmuCheckResult: null,
            dappRefundStatusId: {
              id: '10',
              parentId: null,
              nameRu: 'Принято',
              nameKz: 'Принято',
              code: '00010',
              version: 1.0,
            },
            ddenyReasonId: null,
            drefundReasonId: {
              id: '9',
              parentId: null,
              nameRu: 'Плательщиком или банком дважды перечислено',
              nameKz: 'Плательщиком или банком дважды перечислено',
              code: '9',
              version: 1.0,
            },
          },
          {
            id: 'E94C941ECF7740609DC2D02ED8A8352C',
            lastPayDate: null,
            payAmount: '450.00',
            refundEntryDate: '22.10.2018',
            appPayerDate: '19.10.2018',
            appEndDate: null,
            entryDate: '22.10.2018 12:43',
            receiptAppdateToFsms: null,
            refundDate: null,
            lastMedcarePayCount: null,
            personIin: '731201401557',
            personSurname: 'КАРЫБАЕВА',
            personFirstname: 'ЗАМЗАГУЛ',
            personPatronname: 'БЕКЕНОВНА',
            medinsStatus: null,
            refundPayAmount: 450.0,
            refundStatus: null,
            appRefundStatus: 1,
            refundStatusText: null,
            refundDocumentList: null,
            daysLeft: null,
            changeDate: '22.10.2018 12:43',
            wsStatus: 0,
            wsStatusMessage: null,
            payPeriod: '022018',
            outPayOrderNum: 51287,
            applicationId: {
              id: 'AD511E558DC7498FB33F4B0115065541',
              appNumber: '8994',
              appDate: '22.10.2018',
              payOrderDate: '23.07.2018',
              payOrderNum: '657578   ',
              reference: 'IOA0000000300225',
              refundCount: 4,
              receiptAppdateToFsms: null,
              appEndDate: null,
              dknpId: {
                id: '121',
                parentId: null,
                nameRu: 'Отчисления на обязательное социальное медицинское страхование',
                nameKz: null,
                code: null,
                shortname: 'Обяз.соц.мед.страх.',
                knpType: '1',
                letter: null,
                shortnameKz: null,
              },
            },
            gcvpReference: 'GCVP-00039070777',
            gcvpOrderNum: '37292379 ',
            gcvpOrderDate: '23.07.2018',
            rpmuCheckResult: null,
            dappRefundStatusId: {
              id: '10',
              parentId: null,
              nameRu: 'Принято',
              nameKz: 'Принято',
              code: '00010',
              version: 1.0,
            },
            ddenyReasonId: null,
            drefundReasonId: {
              id: '9',
              parentId: null,
              nameRu: 'Плательщиком или банком дважды перечислено',
              nameKz: 'Плательщиком или банком дважды перечислено',
              code: '9',
              version: 1.0,
            },
          },
          {
            id: '3872890E9A9F46AAB67B754020E645F9',
            lastPayDate: null,
            payAmount: '833.00',
            refundEntryDate: '22.10.2018',
            appPayerDate: '22.10.2018',
            appEndDate: null,
            entryDate: '22.10.2018 17:51',
            receiptAppdateToFsms: null,
            refundDate: null,
            lastMedcarePayCount: null,
            personIin: '801218301320',
            personSurname: 'ШПЕКОВ',
            personFirstname: 'АЗАТ',
            personPatronname: 'САЛИМОВИЧ',
            medinsStatus: null,
            refundPayAmount: 833.0,
            refundStatus: null,
            appRefundStatus: 1,
            refundStatusText: null,
            refundDocumentList: null,
            daysLeft: null,
            changeDate: '22.10.2018 17:51',
            wsStatus: 0,
            wsStatusMessage: null,
            payPeriod: '082018',
            outPayOrderNum: 51324,
            applicationId: {
              id: 'CFC7944BE75544BDA78790377D9C2E04',
              appNumber: '9232',
              appDate: '22.10.2018',
              payOrderDate: '19.09.2018',
              payOrderNum: '2086     ',
              reference: '5318919277012649',
              refundCount: 1,
              receiptAppdateToFsms: null,
              appEndDate: null,
              dknpId: {
                id: '121',
                parentId: null,
                nameRu: 'Отчисления на обязательное социальное медицинское страхование',
                nameKz: null,
                code: null,
                shortname: 'Обяз.соц.мед.страх.',
                knpType: '1',
                letter: null,
                shortnameKz: null,
              },
            },
            gcvpReference: 'GCVP-00039556609',
            gcvpOrderNum: '38210729 ',
            gcvpOrderDate: '20.09.2018',
            rpmuCheckResult: null,
            dappRefundStatusId: {
              id: '10',
              parentId: null,
              nameRu: 'Принято',
              nameKz: 'Принято',
              code: '00010',
              version: 1.0,
            },
            ddenyReasonId: null,
            drefundReasonId: {
              id: '51E748D88D4637A6E054001B782A74A6',
              parentId: null,
              nameRu: 'Ошибочно перечислены',
              nameKz: null,
              code: '00111',
              version: 1.0,
            },
          },
          {
            id: 'E60DD0F935A241A5B9826E04337D6C19',
            lastPayDate: null,
            payAmount: '1247.00',
            refundEntryDate: '22.10.2018',
            appPayerDate: '17.10.2018',
            appEndDate: null,
            entryDate: '22.10.2018 15:11',
            receiptAppdateToFsms: null,
            refundDate: null,
            lastMedcarePayCount: null,
            personIin: '770715450099',
            personSurname: 'СЕИТОВА',
            personFirstname: 'ИНДИРА',
            personPatronname: 'САПУАНОВНА',
            medinsStatus: null,
            refundPayAmount: 1247.0,
            refundStatus: null,
            appRefundStatus: 1,
            refundStatusText: null,
            refundDocumentList: null,
            daysLeft: null,
            changeDate: '22.10.2018 15:11',
            wsStatus: 0,
            wsStatusMessage: null,
            payPeriod: '012018',
            outPayOrderNum: 51309,
            applicationId: {
              id: '0B1F557C484F4D428E104ED265792040',
              appNumber: '8951',
              appDate: '19.10.2018',
              payOrderDate: '02.02.2018',
              payOrderNum: '72400899 ',
              reference: 'TRE351709239',
              refundCount: 10,
              receiptAppdateToFsms: null,
              appEndDate: null,
              dknpId: {
                id: '121',
                parentId: null,
                nameRu: 'Отчисления на обязательное социальное медицинское страхование',
                nameKz: null,
                code: null,
                shortname: 'Обяз.соц.мед.страх.',
                knpType: '1',
                letter: null,
                shortnameKz: null,
              },
            },
            gcvpReference: 'GCVP-00037805789',
            gcvpOrderNum: '34768765 ',
            gcvpOrderDate: '02.02.2018',
            rpmuCheckResult: null,
            dappRefundStatusId: {
              id: '10',
              parentId: null,
              nameRu: 'Принято',
              nameKz: 'Принято',
              code: '00010',
              version: 1.0,
            },
            ddenyReasonId: null,
            drefundReasonId: {
              id: '51E748D88D4637A6E054001B782A74A6',
              parentId: null,
              nameRu: 'Ошибочно перечислены',
              nameKz: null,
              code: '00111',
              version: 1.0,
            },
          },
          {
            id: '99FD3EB4D56F4018BDB7C8BFCB6C10BE',
            lastPayDate: null,
            payAmount: '1772.00',
            refundEntryDate: '22.10.2018',
            appPayerDate: '17.10.2018',
            appEndDate: null,
            entryDate: '22.10.2018 15:11',
            receiptAppdateToFsms: null,
            refundDate: null,
            lastMedcarePayCount: null,
            personIin: '700116302415',
            personSurname: 'МЫЛТЫКБАЕВ',
            personFirstname: 'ДАУЛЕТ',
            personPatronname: 'ТУРСЫНГАЗЫЕВИЧ',
            medinsStatus: null,
            refundPayAmount: 1772.0,
            refundStatus: null,
            appRefundStatus: 1,
            refundStatusText: null,
            refundDocumentList: null,
            daysLeft: null,
            changeDate: '22.10.2018 15:11',
            wsStatus: 0,
            wsStatusMessage: null,
            payPeriod: '012018',
            outPayOrderNum: 51308,
            applicationId: {
              id: '0B1F557C484F4D428E104ED265792040',
              appNumber: '8951',
              appDate: '19.10.2018',
              payOrderDate: '02.02.2018',
              payOrderNum: '72400899 ',
              reference: 'TRE351709239',
              refundCount: 10,
              receiptAppdateToFsms: null,
              appEndDate: null,
              dknpId: {
                id: '121',
                parentId: null,
                nameRu: 'Отчисления на обязательное социальное медицинское страхование',
                nameKz: null,
                code: null,
                shortname: 'Обяз.соц.мед.страх.',
                knpType: '1',
                letter: null,
                shortnameKz: null,
              },
            },
            gcvpReference: 'GCVP-00037805789',
            gcvpOrderNum: '34768765 ',
            gcvpOrderDate: '02.02.2018',
            rpmuCheckResult: null,
            dappRefundStatusId: {
              id: '10',
              parentId: null,
              nameRu: 'Принято',
              nameKz: 'Принято',
              code: '00010',
              version: 1.0,
            },
            ddenyReasonId: null,
            drefundReasonId: {
              id: '51E748D88D4637A6E054001B782A74A6',
              parentId: null,
              nameRu: 'Ошибочно перечислены',
              nameKz: null,
              code: '00111',
              version: 1.0,
            },
          },
          {
            id: '95627EBBAA814CF1B880AECE2FF75BB9',
            lastPayDate: null,
            payAmount: '1620.00',
            refundEntryDate: '22.10.2018',
            appPayerDate: '17.10.2018',
            appEndDate: null,
            entryDate: '22.10.2018 15:11',
            receiptAppdateToFsms: null,
            refundDate: null,
            lastMedcarePayCount: null,
            personIin: '740602400356',
            personSurname: 'КАЛИЕВА',
            personFirstname: 'АСЕТ',
            personPatronname: 'АХМЕТОВНА',
            medinsStatus: null,
            refundPayAmount: 1620.0,
            refundStatus: null,
            appRefundStatus: 1,
            refundStatusText: null,
            refundDocumentList: null,
            daysLeft: null,
            changeDate: '22.10.2018 15:11',
            wsStatus: 0,
            wsStatusMessage: null,
            payPeriod: '012018',
            outPayOrderNum: 51307,
            applicationId: {
              id: '0B1F557C484F4D428E104ED265792040',
              appNumber: '8951',
              appDate: '19.10.2018',
              payOrderDate: '02.02.2018',
              payOrderNum: '72400899 ',
              reference: 'TRE351709239',
              refundCount: 10,
              receiptAppdateToFsms: null,
              appEndDate: null,
              dknpId: {
                id: '121',
                parentId: null,
                nameRu: 'Отчисления на обязательное социальное медицинское страхование',
                nameKz: null,
                code: null,
                shortname: 'Обяз.соц.мед.страх.',
                knpType: '1',
                letter: null,
                shortnameKz: null,
              },
            },
            gcvpReference: 'GCVP-00037805789',
            gcvpOrderNum: '34768765 ',
            gcvpOrderDate: '02.02.2018',
            rpmuCheckResult: null,
            dappRefundStatusId: {
              id: '10',
              parentId: null,
              nameRu: 'Принято',
              nameKz: 'Принято',
              code: '00010',
              version: 1.0,
            },
            ddenyReasonId: null,
            drefundReasonId: {
              id: '51E748D88D4637A6E054001B782A74A6',
              parentId: null,
              nameRu: 'Ошибочно перечислены',
              nameKz: null,
              code: '00111',
              version: 1.0,
            },
          },
          {
            id: '2657736C188C41DA891A4890318D6250',
            lastPayDate: null,
            payAmount: '2254.00',
            refundEntryDate: '22.10.2018',
            appPayerDate: '17.10.2018',
            appEndDate: null,
            entryDate: '22.10.2018 15:11',
            receiptAppdateToFsms: null,
            refundDate: null,
            lastMedcarePayCount: null,
            personIin: '650823301959',
            personSurname: 'ИМАНКУЛОВ',
            personFirstname: 'ЕРЛАН',
            personPatronname: 'КАБЫЛГАЛИЕВИЧ',
            medinsStatus: null,
            refundPayAmount: 2254.0,
            refundStatus: null,
            appRefundStatus: 1,
            refundStatusText: null,
            refundDocumentList: null,
            daysLeft: null,
            changeDate: '22.10.2018 15:11',
            wsStatus: 0,
            wsStatusMessage: null,
            payPeriod: '012018',
            outPayOrderNum: 51306,
            applicationId: {
              id: '0B1F557C484F4D428E104ED265792040',
              appNumber: '8951',
              appDate: '19.10.2018',
              payOrderDate: '02.02.2018',
              payOrderNum: '72400899 ',
              reference: 'TRE351709239',
              refundCount: 10,
              receiptAppdateToFsms: null,
              appEndDate: null,
              dknpId: {
                id: '121',
                parentId: null,
                nameRu: 'Отчисления на обязательное социальное медицинское страхование',
                nameKz: null,
                code: null,
                shortname: 'Обяз.соц.мед.страх.',
                knpType: '1',
                letter: null,
                shortnameKz: null,
              },
            },
            gcvpReference: 'GCVP-00037805789',
            gcvpOrderNum: '34768765 ',
            gcvpOrderDate: '02.02.2018',
            rpmuCheckResult: null,
            dappRefundStatusId: {
              id: '10',
              parentId: null,
              nameRu: 'Принято',
              nameKz: 'Принято',
              code: '00010',
              version: 1.0,
            },
            ddenyReasonId: null,
            drefundReasonId: {
              id: '51E748D88D4637A6E054001B782A74A6',
              parentId: null,
              nameRu: 'Ошибочно перечислены',
              nameKz: null,
              code: '00111',
              version: 1.0,
            },
          },
          {
            id: '0D259975ADF546A191703144B9C6205C',
            lastPayDate: null,
            payAmount: '2559.00',
            refundEntryDate: '22.10.2018',
            appPayerDate: '17.10.2018',
            appEndDate: null,
            entryDate: '22.10.2018 15:11',
            receiptAppdateToFsms: null,
            refundDate: null,
            lastMedcarePayCount: null,
            personIin: '640808302468',
            personSurname: 'ЖАРУЛЛАЕВ',
            personFirstname: 'ШАХИМУРАТ',
            personPatronname: 'РАБУЛЛАЕВИЧ',
            medinsStatus: null,
            refundPayAmount: 2559.0,
            refundStatus: null,
            appRefundStatus: 1,
            refundStatusText: null,
            refundDocumentList: null,
            daysLeft: null,
            changeDate: '22.10.2018 15:11',
            wsStatus: 0,
            wsStatusMessage: null,
            payPeriod: '012018',
            outPayOrderNum: 51305,
            applicationId: {
              id: '0B1F557C484F4D428E104ED265792040',
              appNumber: '8951',
              appDate: '19.10.2018',
              payOrderDate: '02.02.2018',
              payOrderNum: '72400899 ',
              reference: 'TRE351709239',
              refundCount: 10,
              receiptAppdateToFsms: null,
              appEndDate: null,
              dknpId: {
                id: '121',
                parentId: null,
                nameRu: 'Отчисления на обязательное социальное медицинское страхование',
                nameKz: null,
                code: null,
                shortname: 'Обяз.соц.мед.страх.',
                knpType: '1',
                letter: null,
                shortnameKz: null,
              },
            },
            gcvpReference: 'GCVP-00037805789',
            gcvpOrderNum: '34768765 ',
            gcvpOrderDate: '02.02.2018',
            rpmuCheckResult: null,
            dappRefundStatusId: {
              id: '10',
              parentId: null,
              nameRu: 'Принято',
              nameKz: 'Принято',
              code: '00010',
              version: 1.0,
            },
            ddenyReasonId: null,
            drefundReasonId: {
              id: '51E748D88D4637A6E054001B782A74A6',
              parentId: null,
              nameRu: 'Ошибочно перечислены',
              nameKz: null,
              code: '00111',
              version: 1.0,
            },
          },
          {
            id: 'CC07293BCFA9467ABAAE85CEC22ECADD',
            lastPayDate: null,
            payAmount: '2100.00',
            refundEntryDate: '22.10.2018',
            appPayerDate: '17.10.2018',
            appEndDate: null,
            entryDate: '22.10.2018 15:11',
            receiptAppdateToFsms: null,
            refundDate: null,
            lastMedcarePayCount: null,
            personIin: '621010302607',
            personSurname: 'ДУЙСЕНБАЕВ',
            personFirstname: 'ЖУМАБЕК',
            personPatronname: 'ЖУМАТАЕВИЧ',
            medinsStatus: null,
            refundPayAmount: 2100.0,
            refundStatus: null,
            appRefundStatus: 1,
            refundStatusText: null,
            refundDocumentList: null,
            daysLeft: null,
            changeDate: '22.10.2018 15:11',
            wsStatus: 0,
            wsStatusMessage: null,
            payPeriod: '012018',
            outPayOrderNum: 51304,
            applicationId: {
              id: '0B1F557C484F4D428E104ED265792040',
              appNumber: '8951',
              appDate: '19.10.2018',
              payOrderDate: '02.02.2018',
              payOrderNum: '72400899 ',
              reference: 'TRE351709239',
              refundCount: 10,
              receiptAppdateToFsms: null,
              appEndDate: null,
              dknpId: {
                id: '121',
                parentId: null,
                nameRu: 'Отчисления на обязательное социальное медицинское страхование',
                nameKz: null,
                code: null,
                shortname: 'Обяз.соц.мед.страх.',
                knpType: '1',
                letter: null,
                shortnameKz: null,
              },
            },
            gcvpReference: 'GCVP-00037805789',
            gcvpOrderNum: '34768765 ',
            gcvpOrderDate: '02.02.2018',
            rpmuCheckResult: null,
            dappRefundStatusId: {
              id: '10',
              parentId: null,
              nameRu: 'Принято',
              nameKz: 'Принято',
              code: '00010',
              version: 1.0,
            },
            ddenyReasonId: null,
            drefundReasonId: {
              id: '51E748D88D4637A6E054001B782A74A6',
              parentId: null,
              nameRu: 'Ошибочно перечислены',
              nameKz: null,
              code: '00111',
              version: 1.0,
            },
          },
          {
            id: '973EF2E9DCBC44ACAC77866AD9C413AB',
            lastPayDate: null,
            payAmount: '2450.00',
            refundEntryDate: '22.10.2018',
            appPayerDate: '17.10.2018',
            appEndDate: null,
            entryDate: '22.10.2018 15:11',
            receiptAppdateToFsms: null,
            refundDate: null,
            lastMedcarePayCount: null,
            personIin: '640203350449',
            personSurname: 'ГУСЕВ',
            personFirstname: 'ПЕТР',
            personPatronname: 'АНДРЕЕВИЧ',
            medinsStatus: null,
            refundPayAmount: 2450.0,
            refundStatus: null,
            appRefundStatus: 1,
            refundStatusText: null,
            refundDocumentList: null,
            daysLeft: null,
            changeDate: '22.10.2018 15:11',
            wsStatus: 0,
            wsStatusMessage: null,
            payPeriod: '012018',
            outPayOrderNum: 51303,
            applicationId: {
              id: '0B1F557C484F4D428E104ED265792040',
              appNumber: '8951',
              appDate: '19.10.2018',
              payOrderDate: '02.02.2018',
              payOrderNum: '72400899 ',
              reference: 'TRE351709239',
              refundCount: 10,
              receiptAppdateToFsms: null,
              appEndDate: null,
              dknpId: {
                id: '121',
                parentId: null,
                nameRu: 'Отчисления на обязательное социальное медицинское страхование',
                nameKz: null,
                code: null,
                shortname: 'Обяз.соц.мед.страх.',
                knpType: '1',
                letter: null,
                shortnameKz: null,
              },
            },
            gcvpReference: 'GCVP-00037805789',
            gcvpOrderNum: '34768765 ',
            gcvpOrderDate: '02.02.2018',
            rpmuCheckResult: null,
            dappRefundStatusId: {
              id: '10',
              parentId: null,
              nameRu: 'Принято',
              nameKz: 'Принято',
              code: '00010',
              version: 1.0,
            },
            ddenyReasonId: null,
            drefundReasonId: {
              id: '51E748D88D4637A6E054001B782A74A6',
              parentId: null,
              nameRu: 'Ошибочно перечислены',
              nameKz: null,
              code: '00111',
              version: 1.0,
            },
          },
          {
            id: '06D99163A64F4D578E7DF95641CB923A',
            lastPayDate: null,
            payAmount: '1935.00',
            refundEntryDate: '22.10.2018',
            appPayerDate: '17.10.2018',
            appEndDate: null,
            entryDate: '22.10.2018 15:11',
            receiptAppdateToFsms: null,
            refundDate: null,
            lastMedcarePayCount: null,
            personIin: '680110303082',
            personSurname: 'БОНДАРЕВ',
            personFirstname: 'ВЛАДИМИР',
            personPatronname: 'ВИКТОРОВИЧ',
            medinsStatus: null,
            refundPayAmount: 1935.0,
            refundStatus: null,
            appRefundStatus: 1,
            refundStatusText: null,
            refundDocumentList: null,
            daysLeft: null,
            changeDate: '22.10.2018 15:11',
            wsStatus: 0,
            wsStatusMessage: null,
            payPeriod: '012018',
            outPayOrderNum: 51302,
            applicationId: {
              id: '0B1F557C484F4D428E104ED265792040',
              appNumber: '8951',
              appDate: '19.10.2018',
              payOrderDate: '02.02.2018',
              payOrderNum: '72400899 ',
              reference: 'TRE351709239',
              refundCount: 10,
              receiptAppdateToFsms: null,
              appEndDate: null,
              dknpId: {
                id: '121',
                parentId: null,
                nameRu: 'Отчисления на обязательное социальное медицинское страхование',
                nameKz: null,
                code: null,
                shortname: 'Обяз.соц.мед.страх.',
                knpType: '1',
                letter: null,
                shortnameKz: null,
              },
            },
            gcvpReference: 'GCVP-00037805789',
            gcvpOrderNum: '34768765 ',
            gcvpOrderDate: '02.02.2018',
            rpmuCheckResult: null,
            dappRefundStatusId: {
              id: '10',
              parentId: null,
              nameRu: 'Принято',
              nameKz: 'Принято',
              code: '00010',
              version: 1.0,
            },
            ddenyReasonId: null,
            drefundReasonId: {
              id: '51E748D88D4637A6E054001B782A74A6',
              parentId: null,
              nameRu: 'Ошибочно перечислены',
              nameKz: null,
              code: '00111',
              version: 1.0,
            },
          },
          {
            id: '6A6A4A3F6B834243BE4E05031F83E277',
            lastPayDate: null,
            payAmount: '1797.00',
            refundEntryDate: '22.10.2018',
            appPayerDate: '17.10.2018',
            appEndDate: null,
            entryDate: '22.10.2018 15:11',
            receiptAppdateToFsms: null,
            refundDate: null,
            lastMedcarePayCount: null,
            personIin: '700127302777',
            personSurname: 'АЗАМАТОВ',
            personFirstname: 'САБЫРГАЛИ',
            personPatronname: 'КАИРБОЛАТОВИЧ',
            medinsStatus: null,
            refundPayAmount: 1797.0,
            refundStatus: null,
            appRefundStatus: 1,
            refundStatusText: null,
            refundDocumentList: null,
            daysLeft: null,
            changeDate: '22.10.2018 15:11',
            wsStatus: 0,
            wsStatusMessage: null,
            payPeriod: '012018',
            outPayOrderNum: 51301,
            applicationId: {
              id: '0B1F557C484F4D428E104ED265792040',
              appNumber: '8951',
              appDate: '19.10.2018',
              payOrderDate: '02.02.2018',
              payOrderNum: '72400899 ',
              reference: 'TRE351709239',
              refundCount: 10,
              receiptAppdateToFsms: null,
              appEndDate: null,
              dknpId: {
                id: '121',
                parentId: null,
                nameRu: 'Отчисления на обязательное социальное медицинское страхование',
                nameKz: null,
                code: null,
                shortname: 'Обяз.соц.мед.страх.',
                knpType: '1',
                letter: null,
                shortnameKz: null,
              },
            },
            gcvpReference: 'GCVP-00037805789',
            gcvpOrderNum: '34768765 ',
            gcvpOrderDate: '02.02.2018',
            rpmuCheckResult: null,
            dappRefundStatusId: {
              id: '10',
              parentId: null,
              nameRu: 'Принято',
              nameKz: 'Принято',
              code: '00010',
              version: 1.0,
            },
            ddenyReasonId: null,
            drefundReasonId: {
              id: '51E748D88D4637A6E054001B782A74A6',
              parentId: null,
              nameRu: 'Ошибочно перечислены',
              nameKz: null,
              code: '00111',
              version: 1.0,
            },
          },
          {
            id: 'F83632ECE881416CAB52E4D7AE377B5C',
            lastPayDate: null,
            payAmount: '1935.00',
            refundEntryDate: '22.10.2018',
            appPayerDate: '17.10.2018',
            appEndDate: null,
            entryDate: '22.10.2018 15:11',
            receiptAppdateToFsms: null,
            refundDate: null,
            lastMedcarePayCount: null,
            personIin: '590110300316',
            personSurname: 'АБИТБЕКОВ',
            personFirstname: 'ЖЕТИГЕН',
            personPatronname: 'ШЫНЫБЕКОВИЧ',
            medinsStatus: null,
            refundPayAmount: 1935.0,
            refundStatus: null,
            appRefundStatus: 1,
            refundStatusText: null,
            refundDocumentList: null,
            daysLeft: null,
            changeDate: '22.10.2018 15:11',
            wsStatus: 0,
            wsStatusMessage: null,
            payPeriod: '012018',
            outPayOrderNum: 51300,
            applicationId: {
              id: '0B1F557C484F4D428E104ED265792040',
              appNumber: '8951',
              appDate: '19.10.2018',
              payOrderDate: '02.02.2018',
              payOrderNum: '72400899 ',
              reference: 'TRE351709239',
              refundCount: 10,
              receiptAppdateToFsms: null,
              appEndDate: null,
              dknpId: {
                id: '121',
                parentId: null,
                nameRu: 'Отчисления на обязательное социальное медицинское страхование',
                nameKz: null,
                code: null,
                shortname: 'Обяз.соц.мед.страх.',
                knpType: '1',
                letter: null,
                shortnameKz: null,
              },
            },
            gcvpReference: 'GCVP-00037805789',
            gcvpOrderNum: '34768765 ',
            gcvpOrderDate: '02.02.2018',
            rpmuCheckResult: null,
            dappRefundStatusId: {
              id: '10',
              parentId: null,
              nameRu: 'Принято',
              nameKz: 'Принято',
              code: '00010',
              version: 1.0,
            },
            ddenyReasonId: null,
            drefundReasonId: {
              id: '51E748D88D4637A6E054001B782A74A6',
              parentId: null,
              nameRu: 'Ошибочно перечислены',
              nameKz: null,
              code: '00111',
              version: 1.0,
            },
          },
          {
            id: '92D5475ADF23415099A647E85840ACE3',
            lastPayDate: null,
            payAmount: '425.00',
            refundEntryDate: '22.10.2018',
            appPayerDate: '08.10.2018',
            appEndDate: '25.10.2018',
            entryDate: '22.10.2018 15:05',
            receiptAppdateToFsms: '17.10.2018',
            refundDate: null,
            lastMedcarePayCount: null,
            personIin: '850803402503',
            personSurname: 'САРБАСОВА',
            personFirstname: 'ЭЛЬВИРА',
            personPatronname: 'ДУЙСЕНГАЛИЕВНА',
            medinsStatus: null,
            refundPayAmount: 425.0,
            refundStatus: 2,
            appRefundStatus: 1,
            refundStatusText: null,
            refundDocumentList: null,
            daysLeft: null,
            changeDate: '22.10.2018 15:05',
            wsStatus: 0,
            wsStatusMessage: null,
            payPeriod: '052018',
            outPayOrderNum: 51299,
            applicationId: {
              id: '074AC52DFC89483FB49C6076284CB0CE',
              appNumber: '7852',
              appDate: '22.10.2018',
              payOrderDate: '23.08.2018',
              payOrderNum: '002225978',
              reference: 'SB18824461967902',
              refundCount: 1,
              receiptAppdateToFsms: '17.10.2018',
              appEndDate: '25.10.2018',
              dknpId: {
                id: '121',
                parentId: null,
                nameRu: 'Отчисления на обязательное социальное медицинское страхование',
                nameKz: null,
                code: null,
                shortname: 'Обяз.соц.мед.страх.',
                knpType: '1',
                letter: null,
                shortnameKz: null,
              },
            },
            gcvpReference: 'GCVP-00039325545',
            gcvpOrderNum: '37801881 ',
            gcvpOrderDate: '25.08.2018',
            rpmuCheckResult: 'Не соответствует дата рождения;',
            dappRefundStatusId: {
              id: '4',
              parentId: null,
              nameRu: 'Обработано - отказано',
              nameKz: null,
              code: '00004',
              version: 1.0,
            },
            ddenyReasonId: {
              id: '1',
              parentId: null,
              nameRu: 'Частичный возврат по одному участнику',
              nameKz: 'Частичный возврат по одному участнику',
              code: '1',
              version: 1.0,
            },
            drefundReasonId: {
              id: '9',
              parentId: null,
              nameRu: 'Плательщиком или банком дважды перечислено',
              nameKz: 'Плательщиком или банком дважды перечислено',
              code: '9',
              version: 1.0,
            },
          },
          {
            id: 'F2458D2B3C8D40E7B0307D51CB9D1699',
            lastPayDate: null,
            payAmount: '450.00',
            refundEntryDate: '22.10.2018',
            appPayerDate: '19.10.2018',
            appEndDate: null,
            entryDate: '22.10.2018 12:43',
            receiptAppdateToFsms: null,
            refundDate: null,
            lastMedcarePayCount: null,
            personIin: '731201401557',
            personSurname: 'КАРЫБАЕВА',
            personFirstname: 'ЗАМЗАГУЛ',
            personPatronname: 'БЕКЕНОВНА',
            medinsStatus: null,
            refundPayAmount: 450.0,
            refundStatus: null,
            appRefundStatus: 1,
            refundStatusText: null,
            refundDocumentList: null,
            daysLeft: null,
            changeDate: '22.10.2018 12:43',
            wsStatus: 0,
            wsStatusMessage: null,
            payPeriod: '062018',
            outPayOrderNum: 51288,
            applicationId: {
              id: 'AD511E558DC7498FB33F4B0115065541',
              appNumber: '8994',
              appDate: '22.10.2018',
              payOrderDate: '23.07.2018',
              payOrderNum: '657578   ',
              reference: 'IOA0000000300225',
              refundCount: 4,
              receiptAppdateToFsms: null,
              appEndDate: null,
              dknpId: {
                id: '121',
                parentId: null,
                nameRu: 'Отчисления на обязательное социальное медицинское страхование',
                nameKz: null,
                code: null,
                shortname: 'Обяз.соц.мед.страх.',
                knpType: '1',
                letter: null,
                shortnameKz: null,
              },
            },
            gcvpReference: 'GCVP-00039070777',
            gcvpOrderNum: '37292379 ',
            gcvpOrderDate: '23.07.2018',
            rpmuCheckResult: null,
            dappRefundStatusId: {
              id: '10',
              parentId: null,
              nameRu: 'Принято',
              nameKz: 'Принято',
              code: '00010',
              version: 1.0,
            },
            ddenyReasonId: null,
            drefundReasonId: {
              id: '9',
              parentId: null,
              nameRu: 'Плательщиком или банком дважды перечислено',
              nameKz: 'Плательщиком или банком дважды перечислено',
              code: '9',
              version: 1.0,
            },
          },
          {
            id: '3B415077BCA0405593EDA3151369451F',
            lastPayDate: null,
            payAmount: '1035.00',
            refundEntryDate: '22.10.2018',
            appPayerDate: '19.10.2018',
            appEndDate: null,
            entryDate: '22.10.2018 12:43',
            receiptAppdateToFsms: null,
            refundDate: null,
            lastMedcarePayCount: null,
            personIin: '970714351661',
            personSurname: 'КРАМСКОЙ',
            personFirstname: 'ВЛАДИСЛАВ',
            personPatronname: 'НИКОЛАЕВИЧ',
            medinsStatus: null,
            refundPayAmount: 1035.0,
            refundStatus: null,
            appRefundStatus: 1,
            refundStatusText: null,
            refundDocumentList: null,
            daysLeft: null,
            changeDate: '22.10.2018 12:43',
            wsStatus: 0,
            wsStatusMessage: null,
            payPeriod: '062018',
            outPayOrderNum: 51286,
            applicationId: {
              id: 'AD511E558DC7498FB33F4B0115065541',
              appNumber: '8994',
              appDate: '22.10.2018',
              payOrderDate: '23.07.2018',
              payOrderNum: '657578   ',
              reference: 'IOA0000000300225',
              refundCount: 4,
              receiptAppdateToFsms: null,
              appEndDate: null,
              dknpId: {
                id: '121',
                parentId: null,
                nameRu: 'Отчисления на обязательное социальное медицинское страхование',
                nameKz: null,
                code: null,
                shortname: 'Обяз.соц.мед.страх.',
                knpType: '1',
                letter: null,
                shortnameKz: null,
              },
            },
            gcvpReference: 'GCVP-00039070777',
            gcvpOrderNum: '37292379 ',
            gcvpOrderDate: '23.07.2018',
            rpmuCheckResult: null,
            dappRefundStatusId: {
              id: '10',
              parentId: null,
              nameRu: 'Принято',
              nameKz: 'Принято',
              code: '00010',
              version: 1.0,
            },
            ddenyReasonId: null,
            drefundReasonId: {
              id: '9',
              parentId: null,
              nameRu: 'Плательщиком или банком дважды перечислено',
              nameKz: 'Плательщиком или банком дважды перечислено',
              code: '9',
              version: 1.0,
            },
          },
          {
            id: 'E94C941ECF7740609DC2D02ED8A8352C',
            lastPayDate: null,
            payAmount: '450.00',
            refundEntryDate: '22.10.2018',
            appPayerDate: '19.10.2018',
            appEndDate: null,
            entryDate: '22.10.2018 12:43',
            receiptAppdateToFsms: null,
            refundDate: null,
            lastMedcarePayCount: null,
            personIin: '731201401557',
            personSurname: 'КАРЫБАЕВА',
            personFirstname: 'ЗАМЗАГУЛ',
            personPatronname: 'БЕКЕНОВНА',
            medinsStatus: null,
            refundPayAmount: 450.0,
            refundStatus: null,
            appRefundStatus: 1,
            refundStatusText: null,
            refundDocumentList: null,
            daysLeft: null,
            changeDate: '22.10.2018 12:43',
            wsStatus: 0,
            wsStatusMessage: null,
            payPeriod: '022018',
            outPayOrderNum: 51287,
            applicationId: {
              id: 'AD511E558DC7498FB33F4B0115065541',
              appNumber: '8994',
              appDate: '22.10.2018',
              payOrderDate: '23.07.2018',
              payOrderNum: '657578   ',
              reference: 'IOA0000000300225',
              refundCount: 4,
              receiptAppdateToFsms: null,
              appEndDate: null,
              dknpId: {
                id: '121',
                parentId: null,
                nameRu: 'Отчисления на обязательное социальное медицинское страхование',
                nameKz: null,
                code: null,
                shortname: 'Обяз.соц.мед.страх.',
                knpType: '1',
                letter: null,
                shortnameKz: null,
              },
            },
            gcvpReference: 'GCVP-00039070777',
            gcvpOrderNum: '37292379 ',
            gcvpOrderDate: '23.07.2018',
            rpmuCheckResult: null,
            dappRefundStatusId: {
              id: '10',
              parentId: null,
              nameRu: 'Принято',
              nameKz: 'Принято',
              code: '00010',
              version: 1.0,
            },
            ddenyReasonId: null,
            drefundReasonId: {
              id: '9',
              parentId: null,
              nameRu: 'Плательщиком или банком дважды перечислено',
              nameKz: 'Плательщиком или банком дважды перечислено',
              code: '9',
              version: 1.0,
            },
          },
          {
            id: '3872890E9A9F46AAB67B754020E645F9',
            lastPayDate: null,
            payAmount: '833.00',
            refundEntryDate: '22.10.2018',
            appPayerDate: '22.10.2018',
            appEndDate: null,
            entryDate: '22.10.2018 17:51',
            receiptAppdateToFsms: null,
            refundDate: null,
            lastMedcarePayCount: null,
            personIin: '801218301320',
            personSurname: 'ШПЕКОВ',
            personFirstname: 'АЗАТ',
            personPatronname: 'САЛИМОВИЧ',
            medinsStatus: null,
            refundPayAmount: 833.0,
            refundStatus: null,
            appRefundStatus: 1,
            refundStatusText: null,
            refundDocumentList: null,
            daysLeft: null,
            changeDate: '22.10.2018 17:51',
            wsStatus: 0,
            wsStatusMessage: null,
            payPeriod: '082018',
            outPayOrderNum: 51324,
            applicationId: {
              id: 'CFC7944BE75544BDA78790377D9C2E04',
              appNumber: '9232',
              appDate: '22.10.2018',
              payOrderDate: '19.09.2018',
              payOrderNum: '2086     ',
              reference: '5318919277012649',
              refundCount: 1,
              receiptAppdateToFsms: null,
              appEndDate: null,
              dknpId: {
                id: '121',
                parentId: null,
                nameRu: 'Отчисления на обязательное социальное медицинское страхование',
                nameKz: null,
                code: null,
                shortname: 'Обяз.соц.мед.страх.',
                knpType: '1',
                letter: null,
                shortnameKz: null,
              },
            },
            gcvpReference: 'GCVP-00039556609',
            gcvpOrderNum: '38210729 ',
            gcvpOrderDate: '20.09.2018',
            rpmuCheckResult: null,
            dappRefundStatusId: {
              id: '10',
              parentId: null,
              nameRu: 'Принято',
              nameKz: 'Принято',
              code: '00010',
              version: 1.0,
            },
            ddenyReasonId: null,
            drefundReasonId: {
              id: '51E748D88D4637A6E054001B782A74A6',
              parentId: null,
              nameRu: 'Ошибочно перечислены',
              nameKz: null,
              code: '00111',
              version: 1.0,
            },
          },
        ],
      },
    };
  }

  componentDidMount() {

    const columns = [
      {
        title: 'Номер заявки',
        width: 100,
        dataIndex: 'applicationId.appNumber',
      },
      {
        title: 'Дата заявки',
        dataIndex: 'refundEntryDate',
      },
      {
        title: 'Дата поступление',
        dataIndex: 'appPayerDate',
        render: (text, row) => <a
          onClick={()=> {
                this.setState({
                  ShowModal:true,
                  ModalData:{id: row.id,
                    key:'appPayerDate',
                    value:text
                  }
                });
              }}>{text}</a>,
      },
      {
        title: 'Крайняя дата',
        dataIndex: 'gcvpOrderDate',
        render: (text, row) => <a
                            onClick={()=> {
                                    this.setState({
                                      ShowModal:true,
                                      ModalData:{id: row.id,
                                                  key:'gcvpOrderDate',
                                                    value:text
                                                }});
                                              }}
                                >{text}</a>,
      },
      ,
      {
        title: 'Номер платежа',
        dataIndex: 'outPayOrderNum',
      },
      {
        title: 'Дата платежа',
        dataIndex: 'applicationId.payOrderDate',
      },
      {
        title: 'Референс',
        dataIndex: 'gcvpReference',
      },
      ,
      {
        title: 'КНП',
        dataIndex: 'applicationId.dknpId.id',
      },
      ,
      {
        title: 'Возврат',
        dataIndex: 'appRefundStatus',
      },
      {
        title: 'МТ 102',
        fixed: 'right',
        width: 50,
        onCell: record => {
          return {
            onClick: () => {
              console.log(record);
            },
          };
        },
        render: () => (
          <Button>
            <Icon type="database" theme="outlined" />
          </Button>
        ),
      },
      {
        title: 'XML',
        fixed: 'right',
        width: 50,
        onCell: record => {
          return {
            onClick: () => {
              console.log(record);
            },
          };
        },
        render: () => (
          <Button>
            <Icon type="database" theme="outlined" />
          </Button>
        ),
      },
    ];

    columns.forEach((column) => {
      column.sorter = (a, b) => a[column.dataIndex].length - b[column.dataIndex].length;
    });


    this.setState({
      columns: columns,
      dataSource: this.state.DataTable.content.slice(0, 9),
    });
    const children = [];
    for (let i = 10; i < 36; i++) {
      children.push({
        id: i,
        name: 'a' + i,
      });
    }
    this.setState({
      filterForm: [
        {
          name: 'number',
          label: 'Номер заявки:',
          type: 'text',
        },
        {
          name: 'reference',
          label: 'Референс:',
          type: 'text',
        },
        {
          name: 'payNumber',
          label: 'Номер платежного поручения:',
          type: 'text',
        },
        {
          name: 'RefundComeDate',
          label: 'Дата платежного поручения:',
          type: 'betweenDate',
        },
        {
          name: 'RefundFundDate',
          label: 'Дата поступления заявление в Фонд:',
          type: 'betweenDate',
        },
        {
          name: 'knp',
          label: 'КНП:',
          type: 'multibox',
          store: children,
        }
      ]
    })
  }
  componentWillReceiveProps(props) {
  }
  onShowSizeChange = (current, pageSize) => {
    const max = current * pageSize;
    const min = max - pageSize;
    console.log(this.state.DataTable);
    this.setState({
      dataSource: this.state.DataTable.content.slice(min, max),
    });
  };
  handleStandardTableChange = (e) => {
    console.log(e);
  }
  toggleSearcher = () => {
    this.setState({
      isSearcher: false,
      searchercont: 6,
      tablecont: 18
    });
  }
  hideleft() {
      this.setState({
        searchercont: 0,
        tablecont: 24
      });
  }
  resetshow(e) {
    console.log(e);
  }


  render() {
    const dateFormat = 'DD.MM.YYYY';
    const { columns, dataSource } = this.state;

    let lastActiveRow = false;
    const SelectableRow = ({ form, index, ...props }) => {

      const trRef = React.createRef();

      return (<EditableContext.Provider value={form}>
        <tr {...props} ref={trRef} onClick={(e) => {

          if (lastActiveRow) {
            lastActiveRow.style.backgroundColor = '';
          }

          lastActiveRow = trRef.current;
          lastActiveRow.style.backgroundColor = '#e6f7ff';

        }}/>
      </EditableContext.Provider>);
    };

    return (
      <PageHeaderWrapper title="ЗАЯВКИ">
        {<ModalChangeDate visible={this.state.ShowModal}
                         resetshow={(e) => {this.resetshow(e)}}
                         dataSource={this.state.ModalData}/>}
        <Col sm={24} md={this.state.searchercont}>
          {!this.state.isSearcher &&
          <Card
            style={{ margin: '0px 5px 10px 0px', borderRadius: '5px' }}
            type="inner"
            title="Фильтр"
            extra={<Button onClick={event => this.hideleft()}>х</Button>}
          >
            <GridFilter
              clearFilter={()=>{}}
              applyFilter={()=>{}}
              filterForm={this.state.filterForm}
              dateFormat={dateFormat}/>
          </Card>}
        </Col>
        <Col sm={24} md={this.state.tablecont}>
        <Card style={{ margin: '0px 5px 10px 0px', borderRadius: '5px' }}>
          <Row >
            <Button onClick={()=>{this.toggleSearcher()}}>
              <Icon type="search"/>
            </Button>
            <Button>
              <Icon type="loading"/>Обновить
            </Button>
            <div style={{textAlign: 'right', display: 'inline-block', float: 'right'}}>
              Количество записей:8580
            </div>
          </Row>
          <Row style={{ marginBottom: 20 }}>
            <Table
              components={{
                body: {
                  row: SelectableRow,
                },
              }}
              rowKey={'key'}
              dataSource={dataSource}
              columns={columns}
              size={'small'}
              scroll={{ x: 1100 }}
              onChange={this.handleStandardTableChange}
              pagination={false}
            />
          </Row>
          <Row>
            <Pagination
              style={{ display: 'flex', justifyContent: 'center', alignItems: 'center' }}
              showSizeChanger
              onShowSizeChange={this.onShowSizeChange}
              onChange={this.onShowSizeChange}
              defaultCurrent={1}
              total={50}
            />
          </Row>
        </Card>
        </Col>
      </PageHeaderWrapper>
    );
  }
}

export default Requests;
